export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const REGISTER_VISITOR_REQUEST = "REGISTER_VISITOR_REQUEST";
export const REGISTER_VISITOR_SUCCESS = "REGISTER_VISITOR_SUCCESS";
export const REGISTER_VISITOR_FAIL = "REGISTER_VISITOR_FAIL";

export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAIL = "GET_DEPARTMENTS_FAIL";

export const GET_DEPARTMENT_EMPLOYEES_REQUEST ="GET_DEPARTMENT_EMPLOYEES_REQUEST"
export const GET_DEPARTMENT_EMPLOYEES_SUCCESS ="GET_DEPARTMENT_EMPLOYEES_SUCCESS"
export const GET_DEPARTMENT_EMPLOYEES_FAIL ="GET_DEPARTMENT_EMPLOYEES_FAIL"

